# docker compose file for openEHR ontoserver terminology.openehr.org

services:

  # Caddy - auto-HTTPS web server
  caddy:
    image: caddy
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - caddy-data:/data/
      - caddy-data:/config/
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./staticdocs:/srv/staticdocs

  # postgres - database for ontoserver
  db:
    image: postgres:12
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  # ontoserver - main application
  ontoserver:
    image: quay.io/aehrc/ontoserver:ctsa-6 # !!!! requires access to this private quay.io repo
#    container_name: ontoserver (commented out as unnecessary)
#    read_only: true (application does not work if filesystem is read only!)
    security_opt:
      - no-new-privileges
    depends_on:
      - db
    ports:
      - "8443:8443"
      - "8080:8080"
    environment:
# These two lines are specific to deployment in Australia only
#      - authentication.oauth.endpoint.client_id.0=NCTS_CLIENT_ID
#      - authentication.oauth.endpoint.client_secret.0=NCTS_CLIENT_SECRET
#      - JAVA_OPTS=-Xmx2G        # Minimum
      - JAVA_OPTS=-Xmx8G      # Preferred
    volumes:
      - onto:/var/onto
      - /tmp
      - /var/log

volumes:
  onto:
    driver: local
  pgdata:
    driver: local
  caddy-data:
    driver: local
